### PR TITLE
Run mongoDb files in user data path

### PR DESCRIPTION
**Pull request by d62remi**
When you download a new version of the application , the data is not lost

### CODE REVIEW

**Comment by d62remi** [comment]
You can test with your .electrify/package.json : 

```
{
  "name": "my-electrified-app",
  "main": "index.js",
  "dependencies": {
    "electrify": "2.0.0"
  },
  "dbInUserDataPath":true
}
```

**Comment by arboleya** [comment]
@d62remi Just to let you know, I'm merging this on top of other things I had running locally, and also adding little fixes here and there.

Should be released soon.

Tks

**Comment by d62remi** [comment]
;-)

**Comment by arboleya** [comment]
@d62remi I've release this `preserve_db` thing this week, but just now I realised that I have [fucked](https://github.com/arboleya/electrify/commit/aa05d7b3ddf99cb0aee1e57f3f38a5658ebb3433) up the merge/rebase of your commits, so this `PR` remains open until now and you didn't get into the contributors list. I'm sorry about that. I can't see how to fix this without messing up with the master...

**Comment by arboleya** [comment]
Usage [here](https://github.com/arboleya/electrify#config-electrifyjson).

**Comment by d62remi** [comment]
There is no problem. I'm glad you included this feature ;-)

You are doing a very good job !

Thx

**Pull request closed without merging**
